version: "3.9"
services:

  core:
    image: fm0s/gromox-container:latest
    depends_on:
      db:
        condition: service_started
    volumes:
      - /srv/docker/gromox/certificates:/home/certificates
      - /srv/docker/gromox/services:/home/gromox-services
      - /srv/docker/gromox/plugins:/home/plugins
      - /srv/docker/gromox/links:/home/links
      - /srv/docker/gromox/nginx:/home/nginx
    environment:
      - MARIADB_USER=grommunio
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=grommunio
      - DB_HOST=db
      - ADMIN_PASS=admin
      - FQDN=example.com
      - S6_VERBOSITY=3
    ports:
      - '8443:8443'
    networks:
      proxynet:
        aliases: 
          - grommunio
      default:

  db:
    image: mariadb
    environment:
      - MARIADB_DATABASE=grommunio
      - MARIADB_USER=grommunio
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_ROOT_HOST=%
    volumes:
      - /srv/docker/gromox/db:/var/lib/mysql
    networks:
      default:
        aliases:
          - db

networks:
  # This network has been created separately
  proxynet:
    external: true
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd12:3456:789a:1::/64"
